In [24]:
import threading

def square_val(num):
    print("Square Value {}".format(num*num))
    
def cube_val(num, a):
    print('Cube Number {}'.format(num * num * num))
    
    
t1 = threading.Thread(target=square_val, args=(10,))
t2 = threading.Thread(target=cube_val, args=(3,2))

t1.start()
t1.join()

t2.start()
t2.join()

Square Value 100
Cube Number 27


In [25]:
import _thread
import time

# Function for the thread
def my_own_thread(threadName, delay):
    count = 0
    while count < 5:
        time.sleep(delay)
        count += 1
        print("%s: %s" % (threadName, time.ctime(time.time())))

# Start two threads
try:
    _thread.start_new_thread(my_own_thread, ("Thread 1", 2))
    _thread.start_new_thread(my_own_thread, ("Thread 2", 4))
except:
    print("Error: unable to start thread")






In [26]:
print("%s:%s" % (time.ctime(time.time()),time.ctime(time.time())))

Fri Aug 22 09:16:13 2025:Fri Aug 22 09:16:13 2025


In [27]:
import _thread
import time

def myfun(name,*arg):
    print(name,*arg)
    
name = 'mg mg'

_thread.start_new_thread(myfun, (name,1))
_thread.start_new_thread(myfun, (name,1,2))

time.sleep(5)



mg mgmg mg 1 2
 1


Thread 1: Fri Aug 22 09:16:15 2025
Thread 2: Fri Aug 22 09:16:17 2025
Thread 1: Fri Aug 22 09:16:17 2025


In [28]:
import threading
import time

# Thread lock
LOCK = threading.Lock()

class MyThread(threading.Thread):
    """A derived class which customizes the thread.run method"""
    
    def __init__(self, name, delay):
        threading.Thread.__init__(self)  # Call base constructor
        self._name = name
        self._delay = delay

    def run(self):
        for i in range(5):
            LOCK.acquire()  # Acquire the lock
            try:
                print("Hello From %s - %s" % (self._name, time.ctime(time.time())))
            finally:
                LOCK.release()  # Always release lock, even if error occurs
            time.sleep(self._delay)

# Create Our Threads
a = MyThread("Thread A", 1)
b = MyThread("Thread B", 2)

# Start Our Threads
a.start()
b.start()

# Wait for them both to finish
a.join()
b.join()

# Terminate Message
print("Terminated")


Hello From Thread A - Fri Aug 22 09:16:18 2025
Hello From Thread B - Fri Aug 22 09:16:18 2025
Thread 1: Fri Aug 22 09:16:19 2025
Hello From Thread A - Fri Aug 22 09:16:19 2025
Hello From Thread B - Fri Aug 22 09:16:20 2025
Hello From Thread A - Fri Aug 22 09:16:20 2025
Thread 2: Fri Aug 22 09:16:21 2025
Thread 1: Fri Aug 22 09:16:21 2025
Hello From Thread A - Fri Aug 22 09:16:21 2025
Hello From Thread B - Fri Aug 22 09:16:22 2025
Hello From Thread A - Fri Aug 22 09:16:22 2025
Thread 1: Fri Aug 22 09:16:23 2025
Hello From Thread B - Fri Aug 22 09:16:24 2025
Thread 2: Fri Aug 22 09:16:25 2025
Hello From Thread B - Fri Aug 22 09:16:26 2025
Terminated


In [29]:
!pip install numpy

Thread 2: Fri Aug 22 09:16:29 2025



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
import numpy as np

a = np.array([10,20,30,40,50])

b = np.array([
    [10,20,30,40,50],
    [10,21,31,41,50]
])

c = np.array([
    [[10,20,30,40,50], [10,21,31,41,50]],
    [[10,20,30,40,50], [10,21,31,41,50]],
    [[10,20,30,40,50], [10,21,31,41,50]],
    
    ])

a.ndim
b.shape
c.shape

(3, 2, 5)

In [31]:
d = np.ones((2,3))

d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# range(start, stop, step)
# np.arange(start, stop, setp)
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [33]:
a = np.arange(1, 10, 2)

a[2]

np.int64(5)

In [34]:
b = np.array([
    [1,2,3,4],
    [3,6,9,12],
    [2,4,6,8]
    ])
# b.shape
# b.ndim
b[1]
b[1,2]
b[2,3]

np.int64(8)

In [35]:
c = np.array([
    [[10,20,30,40,50], [10,21,31,41,50]],
    [[10,20,30,40,50], [12,22,33,44,55]],
    [[10,20,30,40,50], [10,21,31,41,50]],
    
    ])

print(c.shape)
c[1,1,3]

(3, 2, 5)


np.int64(44)

In [36]:
a = np.arange(1, 10, 2)

b = np.array([
    [1,2,3,4],
    [3,6,9,12],
    [2,4,6,8]
    ])

c = np.array([
    [[10,20,30,40,50], [10,21,31,41,50]],
    [[10,20,30,40,50], [12,22,33,44,55]],
    [[10,20,30,40,50], [10,21,31,41,50]],
    
    ])

c.shape
c.ndim
b[1,2]
c[1,1,1]

np.int64(22)

In [37]:
a = np.array([10,20,30,40,50,60,70,80,20,45,23])
a[1:4]  #range(start index, stop index +1, step)
a[0:12:2]
a[7:2:-1]



array([80, 70, 60, 50, 40])

In [38]:
b = np.array([
    [1,2,3,4],
    [3,6,9,12],
    [2,4,6,8]
    ])

b[1, 1:3]

array([6, 9])

In [39]:
c = np.array([
    [[10,20,30,40,50], [10,21,31,41,50]],
    [[10,20,30,40,50], [12,22,33,44,55]],
    [[10,20,30,40,50], [10,21,31,41,50]],
    
    ])
c[1,1,1:4 ]

array([22, 33, 44])

In [40]:
a = np.array([10,20,30,40,50,60,70,80,20,45,23])
# sum()
total = np.sum(a)
print(total)

448


In [41]:
b = np.array([
    [1,2,3,4],
    [3,6,9,12],
    [3,6,9,12],
    ])
# print(np.sum(b))
total = np.sum(b, axis=1)
print(total)

[10 30 30]


Thread 2: Fri Aug 22 09:16:33 2025


![alt text](image.png)

In [47]:
# avg()
# mean()
a = np.array([10,20,30,40,50,60,70,80,20,45,23])
b = np.array([
    [1,2,3,4],
    [3,6,9,12],
    [3,6,9,12],
    ])
m = np.mean(a, axis=0)
print(m)

40.72727272727273


In [46]:
a = np.array([10,20,30,40,50,60,70,80,20,45,23])
d = np.std(a)
print(d)

21.54948178702347


In [48]:
a = np.array([10,20,30,40,50,60,70,80,20,45,23])
b = np.array([10,20,30,40,50,60,70,80,20,45,23])
print(a+b)

[ 20  40  60  80 100 120 140 160  40  90  46]
